// Generated by CoffeeScript 1.5.0
var bloodGroup, mongoose, percentileClass, sex, student;

mongoose = require('mongoose');

sex = 'M S'.split(' ');

bloodGroup = 'A+ A- B+ B- O+ O-'.split(' ');

percentileClass = 'd f s '.split(' ');

student = new mongoose.Schema({
  N: {
    f: String,
    m: String,
    l: String
  },
  S: {type:String, enum:sex},
  DoB: Date,
  R: String,
  caste: String,
  blG: {type:String, enum:bloodGroup},
  rNo: Number,
  aNo: Number,
  yoA: Number,
  cD: {
    perma: {
      addr: {
        addr1: String,
        addr2: String,
        district: String,
        state: String,
        pincode: {
          type: Number
        }
      },
      phn: Number
    },
    comm: {
      addr: {
        addr1: String,
        addr2: String,
        district: String,
        state: String,
        pincode: {
          type: Number
        }
      },
      phn: Number
    },
    res: {
      addr: {
        addr1: String,
        addr2: String,
        district: String,
        state: String,
        pincode: {
          type: Number
        }
      },
      phn: Number
    },
    localG: {
      addr: {
        addr1: String,
        addr2: String,
        district: String,
        state: String,
        pincode: {
          type: Number
        }
      },
      phn: Number
    }
  },
  parD: {
    N: {
      f: String,
      m: String,
      l: String
    },
    occupation: String
  },
  aQ: {
    one: {
      course: String,
      board: String,
      regno: Number,
      yoPass: Date,
      score: {
        percentile: Number,
        Class: {type: String, enum:percentileClass}
      }
    },
    two: {
      course: String,
      board: String,
      regno: Number,
      yoPass: Date,
      score: {
        percentile: Number,
        Class: {type: String, enum:percentileClass}
      }
    }
  },
  prjD: {
    title: String,
    guide: String
  },
  extCurr: [String],
  U1: {
    101: Number,
    102: Number,
    103: Number,
    104: Number
  }
}, {
  autoIndex: false
});

module.exports = mongoose.model('student', student);
